### PR TITLE
[Docs] Supabase database

### PR DESCRIPTION
**Pull request by sergical**
## Description

Please provide a brief description of the changes introduced in this pull request.

* Adds a blog post to include steps to use [Supabase](https://supabase.com)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, if necessary.
- [x] I have added tests that prove my fix is effective or my feature works.
- [x] New and existing tests pass locally with my changes.

## Additional Notes

* Want to add Supabase Auth to the authentication section, but it will need to be a bit more involved to achieve feature parody with organization configuration Clerk provides. But happy to add a minimal version as well.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Nice work @sergical! I made a few changes so it matches the other migration guides a bit more, but this is excellent work! We should think about collabing on more Supabase migration guides, like Auth and Realtime.

**Comment by sergical** [comment]
> Nice work @sergical! I made a few changes so it matches the other migration guides a bit more, but this is excellent work! We should think about collabing on more Supabase migration guides, like Auth and Realtime.

Exactly what I was thinking, I'd love to!

**Comment by barsketis** [comment]
I took a stab at integrating supa db based on your docs @sergical , and then auth, using this codebase
https://makerkit.dev/docs/next-supabase-turbo
https://github.com/makerkit/nextjs-saas-starter-kit-lite/tree/main/packages/supabase
https://github.com/makerkit/makerkit/tree/main/packages/data-loader/supabase/nextjs

my first attempt if it helps anyone
https://github.com/barsketis/next-forge-supabase

**Comment by sergical** [comment]
@barsketis great start! I actually use Makerkit for a project and really enjoy their setup.

One thing to keep in mind with Auth is next-forge defaults to Organizations being enabled in Clerk to make the `app` sidebar work with organization switching. 

To implement this in supabase, we'd need to create a few tables to store account memberships as well as a few db webhooks to make sure inviting, permissions, etc are handled. 

A workaround would be to make the default `next-forge` setup a bit more simple and create a feature flag for `Clerk Organizations` which would enable that, but the barebones starter would be single tenant. What do you think @haydenbleasel, would love to know if the organization setup as a default is necessary.

**Comment by barsketis** [comment]
yeah in this repo I commented out the organizations for now, im still testing out supabase but I can put together a cleaner repo + docs on it later once I get the rest of the auth functions working for oauth etc.

ill see if I can get a sample prisma.schema working as well with some basic org and user tables, to get some of the functionality back when you first run the pnpm migrate

**Pull request merged**
