### PR TITLE
Turbo

### PR DESCRIPTION
**Pull request by haydenbleasel**
This pull request includes updates to the `dev` scripts in various `package.json` files to enable Turbopack for faster development builds.

Changes to `dev` scripts:

* [`apps/_docs/package.json`](diffhunk://#diff-fa6cf8e56ddb0c531292e45091342e1bec45035268d025d8e9bb3b5c18e6207cL7-R7): Updated `dev` script to include `--turbopack` option.
* [`apps/api/package.json`](diffhunk://#diff-2c40985d6d91eed8ae85ec1c8e754a85984ee32e156a600d2b7a467423d7e338L6-R6): Updated `dev` script to include `--turbopack` option.
* [`apps/app/package.json`](diffhunk://#diff-15a93da17a40a2a46b85fb22b881b4f9cf1e3df61f06826a7da6e7daa3ba0c66L5-R5): Updated `dev` script to include `--turbopack` option.
* [`apps/web/package.json`](diffhunk://#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8L5-R5): Updated `dev` script to include `--turbopack` option.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `RootLayout` component for improved layout management.
	- Enhanced module resolution with new path mappings in TypeScript configuration.

- **Improvements**
	- Updated development scripts across applications to include the `--turbopack` flag for better performance.
	- Added several new dependencies across applications to expand functionality, including image processing and module handling capabilities.

- **Bug Fixes**
	- No specific bug fixes were noted in this release.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
`api` - looks like root layouts are mandatory with turbopack even if there's no pages.

CleanShot 2024-11-05 at 17 20 05@2x

**Comment by haydenbleasel** [comment]
`app` is throwing a bunch of external-related errors

**Comment by haydenbleasel** [comment]
`web` is doing the same, but also complaining about content-collections:

```
web:dev:  ✓ Compiled / in 9.5s
web:dev:  ⨯ ./node_modules/.pnpm/@esbuild+darwin-arm64@0.21.4/node_modules/@esbuild/darwin-arm64/README.md
web:dev: Unknown module type
web:dev: This module doesn't have an associated type. Use a known file extension, or register a loader for it.
web:dev:
web:dev: Read more: https://nextjs.org/docs/app/api-reference/next-config-js/turbo#webpack-loaders
web:dev:
web:dev:
web:dev:
web:dev: ./node_modules/.pnpm/@esbuild+darwin-arm64@0.21.4/node_modules/@esbuild/darwin-arm64/bin/esbuild
web:dev: Reading source code for parsing failed
web:dev: An unexpected error happened while trying to read the source code to parse: failed to convert rope into string
web:dev:
web:dev: Caused by:
web:dev: - invalid utf-8 sequence of 1 bytes from index 0
web:dev:
web:dev:
web:dev:
web:dev: ./apps/web/app/(home)/components/hero.tsx:3:1
web:dev: Export allPosts doesn't exist in target module
web:dev:   1 | import { Button } from '@repo/design-system/components/ui/button';
web:dev:   2 | import { env } from '@repo/env';
web:dev: > 3 | import { allPosts } from 'content-collections';
web:dev:     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web:dev:   4 | import { MoveRight, PhoneCall } from 'lucide-react';
web:dev:   5 | import Link from 'next/link';
web:dev:   6 |
web:dev:
web:dev: The export allPosts was not found in module [project]/apps/web/content-collections.ts [app-rsc] (ecmascript).
web:dev: Did you mean to import default?
web:dev: All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
web:dev:
web:dev:
web:dev:  ⚠ ./node_modules/.pnpm/@opentelemetry+instrumentation@0.52.1_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/instrumentation/build/esm/platform/node
web:dev: Package import-in-the-middle can't be external
web:dev: The request import-in-the-middle matches serverExternalPackages (or the default list).
web:dev: The request could not be resolved by Node.js from the project directory.
web:dev: Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
web:dev: Try to install it into the project directory by running npm install import-in-the-middle from the project directory.
```

**Comment by timneutkens** [comment]
> `api` - looks like root layouts are mandatory with turbopack even if there's no pages.

Root layout was always required, e.g. for the 404 page which you were requesting there. With Turbopack we can't auto-generate a root layout like it does when running webpack as mentioned in the documentation: https://nextjs.org/docs/architecture/turbopack#unsupported-features

**Comment by timneutkens** [comment]
> but also complaining about content-collections:

This error looks correct, looking at the `content-collections.ts` file it only has a default export `export default defineConfig({` and no `allPosts`

**Comment by timneutkens** [comment]
`Package <packagename> can't be external` are warnings, not errors, that are highlighting cases where packages are being used but are not installed so it can fail when running in production. This was already an issue when you were using webpack, it just never warned you that it was missing. This can be fixed by installing the external packages into the project itself.

**Comment by timneutkens** [comment]
```
web:dev:  ⨯ ./node_modules/.pnpm/@esbuild+darwin-arm64@0.21.4/node_modules/@esbuild/darwin-arm64/README.md
web:dev: Unknown module type
web:dev: This module doesn't have an associated type. Use a known file extension, or register a loader for it.
web:dev:
web:dev: Read more: https://nextjs.org/docs/app/api-reference/next-config-js/turbo#webpack-loaders
web:dev:
web:dev:
web:dev:
web:dev: ./node_modules/.pnpm/@esbuild+darwin-arm64@0.21.4/node_modules/@esbuild/darwin-arm64/bin/esbuild
web:dev: Reading source code for parsing failed
web:dev: An unexpected error happened while trying to read the source code to parse: failed to convert rope into string
web:dev:
web:dev: Caused by:
web:dev: - invalid utf-8 sequence of 1 bytes from index 0
```

This seems to be caused by importing `esbuild` somewhere, seems you're running a compiler on code at runtime, which means you're also running `eval` on untrusted code, sounds unexpected and a potential security vulnerability 🤔

Edit: Did some further digging, it's using `mdx-bundler` at runtime.

**Comment by timneutkens** [comment]
Tried to reproduce it by running `mdx-bundler` but that works fine:

```tsx
import { bundleMDX } from "mdx-bundler";

const mdxSource = `
---
title: Example Post
published: 2021-02-13
description: This is some description
---

# Wahoo

import Demo from './demo'

Here's a **neat** demo:

<Demo />
`.trim();

export default async function MdxBundler() {
  const result = await bundleMDX({
    source: mdxSource,
    files: {
      "./demo.tsx": `
  import * as React from 'react'
  
  function Demo() {
    return <div>Neat demo!</div>
  }
  
  export default Demo
      `,
    },
  });

  const { code, frontmatter } = result;

  return (
    <div>
      <h1>My MDX Blog</h1>
      <pre>{JSON.stringify(frontmatter, null, " ")}</pre>
      <pre>{code}</pre>
    </div>
  );
}
```


Only way I can reproduce the error is adding `"use client"` which causes mdx-bundler to be bundled for the browser and it'll fail on that given that it's not a dependency that works in the browser:

CleanShot 2024-11-06 at 11 47 00@2x

**Comment by haydenbleasel** [comment]
Hey @timneutkens, thanks for taking a look!

1. I've added a root layout, thanks for the link.
2. `content-collections` refers to the [alias](https://github.com/haydenbleasel/next-forge/blob/main/packages/typescript-config/nextjs.json#L15), not the file. It's working in webpack.
3. I'll look into installing the external deps, thanks for the info.

**Comment by timneutkens** [comment]
Wrt 2. I'll take a look at reproducing the alias not applying, might be related to the `extends` or that a file called `content-collections.ts` exists in the root of the project.

**Comment by TheCukitoDev** [comment]
@haydenbleasel I had that error when using the Sentry SDK with turbopack in the new Next 15. It first ask me for the import-in-the-middle when using react 19 RC but when i used the react 18 it asked me for the require-in-the-middle package. You can check the full conversation in https://github.com/getsentry/sentry-javascript/issues/8105

**Pull request merged**
