### PR TITLE
Switch docs to Mintlify

### PR DESCRIPTION
**Pull request by fmerian**

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Looking good. Here's the remaining issues we need to solve:

- Hero background image not showing up
- Need support for co-authoring (custom component)
- `/docs/index` should be `/docs` and `/docs/database/index` should be `/docs/database`
- Fix instances of `// [!code ++]` and `// [!code --]`
- `codeBlock.mode = auto` not working locally

**Comment by fmerian** [comment]
Thanks for the review!

Update 2024-11-08:

- [X] Hero background image not showing up
- [ ] Need support for co-authoring (custom component) 
  - @haydenbleasel What do you have in mind here?
- [ ] `/docs/index` should be `/docs` and `/docs/database/index` should be `/docs/database`
- [ ] Fix instances of // [!code ++] and // [!code --]
- [ ] `codeBlock.mode = auto` not working locally 
  - @haydenbleasel Could you please update the CLI and try again? `npm i -g mintlify@latest`
- [ ] Need to add icons to the sidebar items 
  - @haydenbleasel Do you mean icons for each page?
- [X] Add "next-forge" label to navbar logo

**Comment by fmerian** [comment]
- [ ] Add `Steps` component for migration guides

**Comment by haydenbleasel** [comment]
Ah yep you're right, my global CLI was out of date

**Pull request merged**
