### PR TITLE
Add CodeRabbit AI Code Review Integration

### PR DESCRIPTION
**Pull request by tyaga001**
This PR proposes adding [CodeRabbit AI](https://www.coderabbit.ai/) as the automated code review tool to enhance the development workflow. 

Key benefits I personally see in the last 30 days of using this dev tool:

- automated code quality checks and best practices enforcement
- real-time PR summaries and documentation improvements
- TypeScript/React-specific insights
- best part is it's free for [open source ](https://www.coderabbit.ai/pricing) projects 
- seamless GitHub integration 

Implementation Steps:
1. Added `.coderabbit.yaml` configuration

Configuration I added for now:
- set up with "chill" profile for balanced feedback
- added specific path instructions for TS/TSX files
- configured auto-review for main/develop branches
- integrated essential linting tools (Biome, ESLint)
- added path filters to ignore build artifacts

I can update the docs if you like it.

### CODE REVIEW

**Comment by haydenbleasel** [comment]
Thanks @tyaga001! Out of curiosity, what sort of errors do you see Coderabbit catching vs CodeQL, and what alternatives are there?

CR looks cool, just doing the due diligence 😂

**Comment by aravindputrevu** [comment]
@haydenbleasel I work at CodeRabbit; you don't need to write CodeQL. We do that and highlight important issues. 

I'll add some sample PRs below; otherwise, you can check from a bunch in [the wild](https://github.com/search?q=coderabbitai&type=pullrequests). 

Longer explanation:

* CodeRabbit provides well-reasoned code review comments along with one-click fixes, such as Refactor Suggestions, Potential Security Vulnerabilities, Typo Checks, and more. 
* If you Don't like the comments, chat in the same context and generate another fix. Don't want to fix it now, raise a GH, Linear, or Jira Issue. Don't like to fix it at all; you can tell to make it an org-level coding standard. 
* CodeRabbit can bring automated linting to your project; you don't need to write lint config. But if you have, CR will pick it up. We recently added functionality to pick up issues from tools like Codacy and Sonar and generate fixes for us in-line. Importantly, we suppress noise and elevate issues that require your attention. 
* It is not just LLMs; you can augment to find Code Intent through [AST Grep](https://ast-grep.github.io/) Rules. You can write on your own OR use some we created through this [OSS repo](https://github.com/coderabbitai/ast-grep-essentials/blob/main/rules/).  
* In addition, we do ephemeral reviews; each PR is a separate sandbox environment. We don't store any of your code, let alone a trace. 

---
https://github.com/sartography/spiff-arena/pull/1233#discussion_r1529013218
https://github.com/kmesiab/equilibria/pull/1#discussion_r1505474270
https://github.com/kamiazya/web-csv-toolbox/pull/60#discussion_r1453463448
https://github.com/openreplay/openreplay/pull/1858#discussion_r1467629285
https://github.com/ls1intum/Artemis/pull/8037#discussion_r1494109998

**Comment by tyaga001** [comment]
@aravindputrevu thanks for details. @haydenbleasel l hope you get the clarification. let me or @aravindputrevu know if you have any more questions. shall I mark the PR ready for review?

**Comment by haydenbleasel** [comment]
@tyaga001 Sure, I'm keen to give it a try. Feel free to mark as ready and I'll merge.

**Comment by tyaga001** [comment]
@haydenbleasel Thanks for being open to trying it out, but it looks like it's not enabled yet. 

Here are the quick steps to enable CodeRabbit:

1. Sign up at coderabbit.ai using your GitHub account.
2. Go to add your repository, choose `next-forge`
3. That's it. CodeRabbit will start reviewing PRs automatically using the config I added.

Let me know if you need any help with the setup. 🐰

**Pull request merged**
